# Generated by Django 3.0.10 on 2020-11-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_picture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Category'),
        ),
    ]
